trigger:
- master

pool: 'Default'

variables:
  imageRepository: 'fiap-cloud-games'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  acrServiceConnection: 'ConexaoAzureContainerRegistry'
  azureSubscription: 'Acimel - PROD(8ad60e49-3122-49d8-b64e-1e7f12380229)'
  resourceGroup: 'FIAP'
  containerAppName: 'api-fiap-cloud-games'
  containerAppEnvironment: 'managedEnvironment-FIAP-8860'
  acrLoginServer: 'acimel.azurecr.io'

stages:
- stage: Build
  displayName: 'Build da Imagem Docker'
  jobs:
  - job: BuildJob
    displayName: 'Build'
    pool: 'Default'
    steps:
    - task: Docker@2
      displayName: 'Build da Imagem'
      inputs:
        command: 'build'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'

- stage: Push
  displayName: 'Push da Imagem para o Azure Container Registry'
  dependsOn: Build
  jobs:
  - job: PushJob
    displayName: 'Push'
    pool: 'Default'
    steps:
    - task: Docker@2
      displayName: 'Push da Imagem para o Azure Container Registry'
      inputs:
        command: 'push'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy no Azure Container App'
  dependsOn: Push
  jobs:
  - job: DeployJob
    displayName: 'Deploy'
    pool: 'Default'
    steps:
    - task: AzureContainerApps@1
      displayName: 'Deploy da Imagem no Azure Container App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        resourceGroup: '$(resourceGroup)'
        containerAppName: '$(containerAppName)'
        imageToDeploy: '$(acrLoginServer)/$(imageRepository):$(tag)'